### ISSUE TITLE
Proto query: why is nuc_mut a repeated field?

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#101]
In `parsimony.proto`, `mut_nuc` is a repeated field where `ref_nuc` and `par_nuc` are not: https://github.com/yatisht/usher/blob/96347744b4096fedf13a825b781b362a8a3ba705/parsimony.proto#L9 

Looking at the code I couldn't immediately see where multiple values could come from, so just raising this query to understand better. No worries if this is just a historical or future-proofing thing.

**Comment by yatisht** [comment]
Hi Theo,

We used a repeated field in order to store multiple bases in case of ambiguous bases in sequences or equally parsimonious states in internal nodes. However, for the trees we release, we parsimony-resolve multiple bases to a single base, so you can just treat it as a vector containing a single element. Does that make sense?

Best,
Yatish

**Comment by theosanderson** [comment]
That makes a lot of sense! Thanks so much for walking me through it 👍
