### ISSUE TITLE
reference sequence for mutations, and tracking amino-acid mutations

### ISSUE THREAD

**Issue by jbloom** [yatisht/usher#111]
I just discovered `UShER`, it's amazing! But I had two questions, one very simple and the other somewhat more complex:

1. Is the reference sequence to which mutations are defined Wuhan/Hu-1 (GenBank MN908947.3)? I assume this is the case, but I couldn't find it clearly documented anywhere. If I am writing pipelines to process `UShER` output, can I assume this reference will stably remain the same?

2. I'm actually interested in counting amino-acid mutations in spike and looking at selection on those. Right now `UShER` outputs nucleotide mutations. Since the virus is still in a pretty low-mutation regime, I can probably safely just determine amino-acid mutations by translating the single-nucleotide changes. But that approach is going to break down as more mutations accumulate and some codons are multiply mutated. Are there commands similar to `matTools summary --mutations` that will make it possible to easily extract amino-acid mutations when codons have multiple nucleotide substitutions and so single-nucleotide mutations can't be directly mapped to amino-acid changes?

**Comment by yatisht** [comment]
Hi Jesse, 

Thank you so much for your kind words and your work. 

1. UShER is not hardwired to any particular reference. The reference sequence for UShER is the same as the reference sequence used in the VCF that is used to generate the mutation-annotated tree (the protobuf file). Having said that, we have been using the Wuhan/Hu-1 (GenBank MN908947.3, RefSeq NC_045512.2) sequence as the reference in our web interface (https://genome.ucsc.edu/cgi-bin/hgPhyloPlace) as well as in our publicly-released mutation-annotated trees (http://hgdownload.soe.ucsc.edu/goldenPath/wuhCor1/UShER_SARS-CoV-2/), and we don't plan to change that.
2. Incidentally, we have also been planning to add this feature to `matUtils`. We will update here as soon as it is made available.

@jmcbroome, let's try to have a high priority for this feature. 

Thanks.

**Comment by russcd** [comment]
This is very helpful feedback. 

We should definitely update the documentation where we are hosting the MATs to indicate that our SARS-CoV-2 MAT is using NC_045512.2.

**Comment by jbloom** [comment]
Great, thanks for the quick and helpful responses on this! Do tag me in when the amino-acid mutation counts (or some easy way to get them) also becomes available.

**Comment by zach-hensel** [comment]
Hi -- also a new UShER user here and this seems a relevant place to put this rather than a new issue. I noticed in a subtree that an Orf3a mutation mutated twice at the same codon, EPI_ISL_2694687 and others, are labeled Q57H rather than with no amino acid mutation (CAG>CGG>CGT = Q>R>R). I don't know if this is a common issue -- it's the first time I've noticed it.

See the subtree around the uploaded sample here: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_549a0_607cc0.json?label=nuc%20mutations:A25562G

Agree it would be awesome to have a good list of mutation events; ideally there'd be columns specifying the parent genotype, nucleotide, and amino acid variations from a tree without common errors (e.g. G142D and D950N). I guess these errors can be identified from reversions and recurrences separated by little sequence space.

**Comment by AngieHinrichs** [comment]
Hi @zach-hensel -- the amino acid translations that you're seeing there are not directly from usher/matUtils; they're added by the [web interface](https://genome.ucsc.edu/cgi-bin/hgPhyloPlace), which currently considers each nucleotide mutation in isolation, so when it's translating the mutation at 25563, it is not considering the mutation at 25562 in the same codon so it's getting the wrong answer as you pointed out.  Thanks for the reminder that we'll have to get it right in more than one place.   [either in both matUtils and usher, or matUtils and the web interface]

Our tree will soon be updated with G142D / D142G (position 21987) masked, so it won't mess up the Delta branch so badly, and are thinking about ways to address the problem of mutations that are unreliable in specific branches of the tree.

If you upload FASTA sequences to the web interface instead of sequence IDs, then the results include downloadable TSV files for each subtree: one with both nucleotide and amino acid changes, and one that focuses on Spike mutations.  Here are the TSVs produced when uploading the FASTA for EPI_ISL_2694687 (renamed to .txt for github):
[usher_samples_hgwdev_angie_397b_6cfcf0.tsv.txt](https://github.com/yatisht/usher/files/6913146/usher_samples_hgwdev_angie_397b_6cfcf0.tsv.txt)
[usher_S_muts_hgwdev_angie_397b_6cfcf0.tsv.txt](https://github.com/yatisht/usher/files/6913145/usher_S_muts_hgwdev_angie_397b_6cfcf0.tsv.txt)
The usher_S_muts TSV is intended as a quick summary of Spike mutations when a bunch of sequences are uploaded together.  The usher_samples TSV lists all nucleotide mutations and amino acid non-synonymous substitutions (indels are ignored at this point).  Unfortunately A25562G and G25563T are translated independently as ORF3a:Q57R and ORF3a:Q57H.  
I will look into fixing that, but no promises about how soon I'll be able to get to that.

**Comment by amkram** [comment]
Hi @jbloom @zach-hensel ,

This feature has been implemented under `matUtils summary --translate`.

See [the docs](https://usher-wiki.readthedocs.io/en/latest/matUtils.html#summary) for details and an example workflow [here](https://usher-wiki.readthedocs.io/en/latest/tutorials.html#example-amino-acid-translation-workflow).

Please let me know if you encounter any issues.

**Comment by yatisht** [comment]
@jbloom and @zach-hensel I am closing this issue since I think it has been resolved now, but let us know if you have further suggestions. Thanks!
