### ISSUE TITLE
Closest neighbour with command line Usher?

### ISSUE THREAD

**Issue by charlesfoster** [yatisht/usher#136]
Hi,

When I use Usher, I normally use the web version through UCSC. I'm playing around with the utils locally, and I'm trying to figure out how to replicate the UCSC result of "Neighboring sample in tree".

So far I run either of the following:

(1)
```
usher --vcf sample123.vcf \
-i public-latest.all.masked.pb.gz \
-k 10 \
-o test.pb.gz
```
Result: `subtree-1-mutations.txt` has 10 samples, including my input sample.

(2)
```
usher --vcf sample123.vcf \
-i public-latest.all.masked.pb.gz \
-o test.pb.gz

matUtils extract -i test.pb.gz \
-j nearest_neighbours.json \
-k "sample123:10"
```
Result: `nearest_neighbours.json` with 10 samples, including my input sample.

Both of these subtrees match that generated by the UCSC implementation - hooray! Except none of the samples in them contain the 'neighboring sample in tree' from the UCSC implementation. If I select a random sample from the GISAID tree (e.g., Netherlands/ZuidHolland_26/2020) and repeat the same procedure, the nearest neighbour from the UCSC implementation (100381 | LR884417.1 | 2020-03-20) rather than itself. Why is this? I think there must be something in the terminology that I'm not quite understanding... 

I guess a summary of what I want to do is place a new sample in the latest protobuf tree download, then extract the closest pre-existing sample in the protobuf tree to my new input sample (e.g., an exact match, or ~1 SNP away). If there is more than >1 sample, or >1 samples with the exact same numbers of mutations different from the input sample, choose one of those samples at random.

Thanks! I've attached the sample vcf, if that helps.
[sample123.txt](https://github.com/yatisht/usher/files/7011628/sample123.txt)

**Comment by yatisht** [comment]
Your issue helped uncover a bug in the logic of getting the nearest subtree in UShER and matUtils (the Genome Browser was using its own logic, which seems correct, to get the nearest neighbor). I have fixed the bug now, and both UShER and matUtils should output the nearest subtrees with the fewest mutations (under topological constraints and ignoring reversal mutations currently) from the sequences being considered. It could take up to a few weeks for this change to be reflected in the Genome Browser subtrees, unfortunately, but please let us know if you still find issues in the output with the `-k` option of the command line tools. 

These changes should also appear in the latest release version ([v0.4.2](https://github.com/yatisht/usher/releases/tag/v0.4.2)) I just created.

**Comment by charlesfoster** [comment]
That's great, thanks. I'm currently installing via conda for ease, but I'll install from github when I get a chance to check it out (and upgrade via conda when available). I'll let you know if the behaviour is still unexpected.

**Comment by yatisht** [comment]
The conda update to v0.4.2 should now be available.

**Comment by AngieHinrichs** [comment]
The web interface finds the 'nearest neighbor' independently from usher's subtrees as you noticed.  Not sure if the details are of interest to you, but just in case, here's how the web interface selects a similar pre-existing sequence.  It finds the deepest pre-existing big tree node on the path to the sequence's final placement (which is sometimes on a new branch with other uploaded sequences; we want to exclude those in this case).  If that node has a child that is a leaf with no mutations of its own (like 100381|LR884417.1|2020-03-20 on the node on which Netherlands/ZuidHolland_26/2020 is placed), then that leaf child is selected as the nearest neighbor.  If the node has no leaf child with no mutations of its own, but the node has leaf children, then the leaf child with the fewest mutations is selected.  If that fails, then we try with the node's parent.  If that still fails, we give up.  Maybe not an optimal method, but it works well enough most of the time.  :)  

So 100381|LR884417.1|2020-03-20 is selected as the nearest neighbor instead of Netherlands/ZuidHolland_26/2020|LR878327.1|2020-03-09 because the sequences are identical from the mutation-annotated tree's point of view, and 100381|LR884417.1|2020-03-20 just happens to come earlier in the list of that node's children; we don't examine sequence names.

[@yatisht fortunately the usher and matUtils executables are treated as data in our release system, so I should be able to get the latest versions out there tomorrow -- unlike web interface code changes which do take 1-4 weeks :b .]

**Comment by charlesfoster** [comment]
Thanks @AngieHinrichs, interesting to know how it works with the web interface. Is there a quick and easy way to replicate this behaviour on the command line with existing `usher` and/or `matUtils` options? Perhaps extract a subtree with k=2 then grok out the other sample?

```
usher --vcf sample123.vcf \
-i public-latest.all.masked.pb.gz \
-k 2 \
-o test.pb.gz

grep -v -e "^node_" -e "sample123" subtree-1-mutations.txt | cut -f1 -d ":" > neighbor.txt
```
or
```
usher --vcf sample123.vcf \
-i public-latest.all.masked.pb.gz \
-o test.pb.gz

matUtils extract -i test.pb.gz \
-j nearest_neighbours.json \
-v neighbours.vcf \
-k "sample123:2"
```

The result for both approaches with sample123 (from the attached vcf in the first post) is England/PHEC-2029B/2020|2020-03-01, which is identical to sample123.

**Comment by AngieHinrichs** [comment]
I think you've answered your own question there @charlesfoster.  :)  That should work fine as long as you try it with one sequence at a time.  If you feed in a bunch of sequences that are similar to each other, then you might get another uploaded sequence as the result instead of a pre-existing sequence.

**Comment by russcd** [comment]
This looks resolved, but feel free to reopen if I am incorrect.
