### ISSUE TITLE
faToVcf download

### ISSUE THREAD

**Issue by jonaudet** [yatisht/usher#140]
Hi,
    On three Ubuntu computers now, I had to change the download of faToVcf in installUbuntu.sh to the following (rsync just refused to work and the address appears not to work at all, at least for me):

wget https://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToVcf

**Comment by yatisht** [comment]
This seems to be related to the permissions on your servers. I retried the commands on an Ubuntu server as well as through Docker and found no issues.

What's the error message that you get?

**Comment by russcd** [comment]
I'm closing this for now, but please feel free to reopen if you cannot resolve this issue.

**Comment by xbello** [comment]
> What's the error message that you get?

```
rsync: [Receiver] failed to connect to hgdownload.soe.ucsc.edu (128.114.119.163): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(139) [Receiver=3.2.7]
```

This is particularly bad when building a docker image, because you have to edit the install[OS].sh script, but then you are out of sync with the github repo. I added:

`RUN wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToVcf`

to install/Dockerfile, and removed the rsync from the installUbuntu.sh. Maybe a "rsync if faToVcf doesn't exist"?

**Comment by xbello** [comment]
> What's the error message that you get?

```
$ rsync -aP rsync://hgdownload.soe.ucsc.edu/genome/admin/exe/linux.x86_64/faToVcf .
rsync: [Receiver] failed to connect to hgdownload.soe.ucsc.edu (128.114.119.163): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(139) [Receiver=3.2.7]
```

This is particularly bad when building a docker image, because you have to edit the installUbuntu.sh script, but then you are out of sync with the github repo. I added:

`RUN wget http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/faToVcf`

to install/Dockerfile, and removed the rsync from the installUbuntu.sh. Maybe a "rsync if faToVcf doesn't exist"?
