### ISSUE TITLE
S:F157S in Taxonium export for AY.4.2 parent

### ISSUE THREAD

**Issue by theosanderson** [yatisht/usher#179]
This is via @mg14 and I haven't had a chance to investigate it in great detail yet. He points out that on Cov2Tree we report a S:F157S on a branch ancestral to AY.4.2 (and propagate this to its children).

![image](https://user-images.githubusercontent.com/19732295/138305849-ea2eba39-2d13-433b-b411-f2f4a22b3f01.png)

This is unlikely given the 156/157 deletion in Delta. Of course in my pipeline I took/take a very error prone approach to mutation calling which I think didn't consider deletions at all, so only raising this for info. The only thing I've had a chance to do is to compare  this to my ([older](https://cov2tree-c8a52kpxq-theosanderson.vercel.app/?blinking=true&xAccessor=time_x&protoUrl=%2Fnodelist.pb.gz&search=%5B%7B%22id%22%3A0.123%2C%22category%22%3A%22name%22%2C%22value%22%3A%22QEUH-1CC1224%22%2C%22enabled%22%3Atrue%2C%22aa_final%22%3A%22V%22%2C%22min_tips%22%3A12%2C%22aa_gene%22%3A%22S%22%2C%22search_for_ids%22%3A%22%22%2C%22aa_pos%22%3A%22222%22%7D%5D&colourBy=%7B%22variable%22%3A%22aa%22%2C%22gene%22%3A%22S%22%2C%22colourLines%22%3Afalse%2C%22residue%22%3A%22222%22%7D&zoomToSearch=-1)) tree produced with my pipeline which doesn't show the same result at 157. I will try to discover more detail about this, such as what the nuc mutation that corresponds to this point is but haven't had a chance yet.

**Comment by theosanderson** [comment]
(Also I haven't ruled out a bug in Taxonium itself)

**Comment by AngieHinrichs** [comment]
It's not a bug in Taxonium, our tree really has a node on the path to AY.4.2 with 3 SNVs together: G22030A,T22031A,T22032G.

I will look at some sequence alignments and see if I can figure out where that's coming from.  I think in theory, if just one sequence added to the tree early on had nucleotide changes at reference positions 22030-22032, and then all the subsequently added sequences had 'N' or '-' at those positions (UShER uses only single-nucleotide changes and treats deletions as Ns) then we would accept those as a match.  

For the record here's the path in the 2021-10-20 full tree (including GISAID sequences; the public tree path has a few more nodes collapsed but is otherwise the same):
```
C14408T > C241T > C3037T > A23403G > G29742T > T22917G > T27638C > G28881T > G210T > C21618G > G29402T > C23604G > C25469T > G24410A > C22995A,C27752T > A28461G > C16466T > T26767C > G15451A > C10029T > C19220T > G28916T > G4181T > C27874T > C6402T > C7124T > G9053T > C8986T > T6402C > A11332G > A11201G > C6402T > C21846T > C7851T > G22030A,T22031A,T22032G > G28248A > T17040C > C25614T,A28248G > C22227T > T21995C
```

**Comment by theosanderson** [comment]
Thanks @AngieHinrichs . I used to know that UShER treated deletions as Ns, but had forgotten! Is the rationale for this that they are just not reported accurately enough?

**Comment by theosanderson** [comment]
No pressure from me to invest time into this. I was flagging because:
- I had forgotten that deletions weren't modelled
- So I thought this might be a bug in how deletions were exported

Sorry slightly scatterbrained atm :)
