### ISSUE TITLE
a split in the BA.3 tree

### ISSUE THREAD

**Issue by shay671** [yatisht/usher#204]
i run the 42 samples categorized in GISAID as BA.3 in USHER.  

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_2c4c6_3c6fa0.json

As can be seen the tree is seems to split

![image](https://user-images.githubusercontent.com/80166370/149651694-6f1fd323-82bd-44ea-8537-a2347d7843c0.png)

I looked at the mutations in the lower part clade and it seems to have the defining mutations of BA.3 without any additions or missings

**Comment by AngieHinrichs** [comment]
Thanks for reporting this.  Sorry it is in a bad state at the moment.  I hope to have it fixed on the main site later tomorrow (Monday) but since it is a holiday, it might have to wait until Tuesday.  

When sequences have only a small subset of the mutations that they should (in particular when Wuhan/Hu-1 reference bases are used instead of N), they sometimes get placed very close to the root of the tree.  Then they can attract sequences that have slightly larger subsets of mutations, and those in turn can attract more, until the branch has enough mutations to compete with real lineage branches.

So far we've been dealing with these by identifying the sequences near the root of these bogus branches (in this case, recent sequences with small subsets of Omicron mutations) and permanently excluding those problematic sequences from the tree.  The sequences that look OK, but that were placed on a bogus-looking branch, are removed but then added back in the next day's build.

We are thinking about better ways to identify problematic sequences so we can exclude them before they cause trouble like this.  With Omicron, we're also having a lot of difficulties with apparent Delta mutations messing up the tree inference, so we'll be thinking about masking more sites as well.

**Comment by russcd** [comment]
I believe this one is resolved.
