### ISSUE TITLE
Root-To-Tip Distance or Path?

### ISSUE THREAD

**Issue by ktmeaton** [yatisht/usher#215]
Is it possible to extract the root-to-distance for each sample, or better yet, the full mutation paths to the root? I'd like to plot these to explore temporal signal in the data. I've explored `matUtils summary` and `matUtils extract`, but haven't quite figured it out. 

One solution I've found is to export the newick string, and then parse it with an external package (ex. `biopython`). But that is very slow and inefficient.

**Comment by yatisht** [comment]
I think the `--all-paths` option in `matUtils extract` should work, right @jmcbroome?

**Comment by jmcbroome** [comment]
You'll specifically want the ```--sample-paths (-S)``` option e.g.  ```matUtils extract -i your.pb -S all_node_paths.txt```, which yields a two column text file containing, in column 1, the sample name, and in column 2, a space and colon delimited text representation of the path of mutations from the root to that sample. 

An example line of output would read:
```
sample_name    node_200:M1 node_3425:M2,M3
```
In this case, the path represented for sample_name is root with no mutations, to child node_200 with mutation 1, to child node_3425 with mutations 2 and 3, to the sample node. If the sample node has private mutations, its name will appear at the end of the path with the mutations in question.

```matUtils extract``` can be a bit hard to navigate. All of our documentation for matUtils is [here](https://usher-wiki.readthedocs.io/en/latest/matUtils.html). Let us know if anything is missing, should be clarified, or is out of date- hope this helps! 

Additionally, if in the future you find yourself needing to extract newicks to biopython to perform some specific operation or some similarly clunky processing issue, even if you have a working method, feel free to drop a github issue or send me an email (jmcbroom@ucsc.edu)- I'm working on an [API](https://github.com/jmcbroome/matreePy) to export useful matUtils functions to python and am always looking to improve the capabilities and usability of our software, in python or otherwise!

**Comment by ktmeaton** [comment]
Great success! It seems very obvious now in retrospect, thank you so much :) I've tested this out with an UShER tree of the ncov/open/global and it's working well.

![usher rtt](https://user-images.githubusercontent.com/14981272/156468047-4e1bfc01-8963-4816-80f9-e5f2d06ab1d8.png)

**Comment by jmcbroome** [comment]
Looks great! I'm going to close out this issue now- always happy to help.
