### ISSUE TITLE
parsimony scores for all samples

### ISSUE THREAD

**Issue by roblanf** [yatisht/usher#7]
I have a suggestion for extending the utility of `--print-parsimony-scores-per-node`. Currently this function calculates parsimony scores of all sequences in the vcf passed via `--vcf`, but users may also want this information for all samples in an existing tree.

It would be great to enable this. There are lots of ways one could implement it, because the data to calculate parsimony scores for existing sequences is already in the `.pb` file, right?

**Comment by roblanf** [comment]
I tried to trick UShER into doing this by passing the `global_samples.vcf` test file with `--vcf`, but it (sensibly) didn't like that:

`WARNING: Ignoring sample Brazil_SPBR-05_2020 as it is already in the tree.`

Maybe one way to do it is to allow users to optionally pass a file of sample names when calling `--print-parsimony-scores-per-node`? The expectation would be that every name in that file is an existing name in the tree (WARNING if not?), and that when a name in that file matches a name in the tree, the parsimony scores for placing that sequence along the whole tree are calculated.

**Comment by yatisht** [comment]
The easiest way to do this is by providing a VCF with modified samples names (like a _BPS suffix) when calling `--print-parsimony-scores-per-node` so that it doesn't collide with an existing sample name in the tree. I could do something like this internally in UShER as well without the user requiring to do it but it's not going to be my current priority.
